on:
  release:
    types:
      - published

name: Build binaries

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            bin_suffix: ""
          - os: macos-latest
            bin_suffix: ""
          - os: windows-latest
            bin_suffix: ".exe"
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --no-default-features --features "vtf bsp"
      - name: List binaries
        run: ls target/release
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: "Upload bsp"
        uses: "actions/upload-release-asset@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: "application/octet-stream"
          asset_name: bsp_${{ matrix.platform.os }}${{ matrix.platform.bin_suffix }}
          asset_path: "target/release/bsp${{ matrix.platform.bin_suffix }}"
          upload_url: ${{ steps.get_release.outputs.upload_url }}
      - name: "Upload gma"
        uses: "actions/upload-release-asset@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: "application/octet-stream"
          asset_name: gma_${{ matrix.platform.os }}${{ matrix.platform.bin_suffix }}
          asset_path: "target/release/gma${{ matrix.platform.bin_suffix }}"
          upload_url: ${{ steps.get_release.outputs.upload_url }}
      - name: "Upload mdl"
        uses: "actions/upload-release-asset@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: "application/octet-stream"
          asset_name: mdl_${{ matrix.platform.os }}${{ matrix.platform.bin_suffix }}
          asset_path: "target/release/mdl${{ matrix.platform.bin_suffix }}"
          upload_url: ${{ steps.get_release.outputs.upload_url }}
      - name: "Upload vtf"
        uses: "actions/upload-release-asset@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: "application/octet-stream"
          asset_name: vtf_${{ matrix.platform.os }}${{ matrix.platform.bin_suffix }}
          asset_path: "target/release/vtf${{ matrix.platform.bin_suffix }}"
          upload_url: ${{ steps.get_release.outputs.upload_url }}
